[project]
site_name = "Class Notes 3AHIF 26/27"
site_url = "https://KooroshHassaniHTL.github.io/Notes-2627/"

nav = [
    { "Startseite" = "index.md" },

    { "Deutsch" = [
        { "Index" = "Mitschrift/DEUTSCH/index.md" },
        { "Konjunktiv" = "Mitschrift/DEUTSCH/konjunktiv.md" }
    ]},

    { "SYP" = [
        { "Index" = "Mitschrift/SYP/index.md" },
        { "Grundbegriffe" = "Mitschrift/SYP/grundbegriffe.md"}
    ]},

    { "POSE" = [
        { "Index" = "Mitschrift/POSE/index.md" },
        { "Comparable" = "Mitschrift/POSE/comparable.md"},
        { "Equals" = "Mitschrift/POSE/equals.md"}
    ]},

    { "DBI" = [
        { "Index" = "Mitschrift/DBI/index.md" },
        { "Grundbegriffe" = "Mitschrift/DBI/grundbegriffe.md"}
    ]}
]
