[project]
site_name = "Class Notes 3AHIF 26/27"
site_url = "https://KooroshHassaniHTL.github.io/Notes-2627/"

nav = [
    { "Startseite" = "index.md" },

    { "Deutsch" = [
        { "Index" = "Mitschrift/DEUTSCH/index.md" }
    ]},

    { "SYP" = [
        { "Index" = "Mitschrift/SYP/index.md" },
        { "Grundbegriffe" = "Mitschrift/SYP/Grundbegriffe.md"}
    ]},

    { "POSE" = [
        { "Index" = "Mitschrift/POSE/index.md" }
    ]}
]
